name: Validate with HACS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation (integration)
        uses: hacs/action@main
        with:
          category: "integration"
          ignore: ""   # do not set this – PRs must not disable checks
